### ISSUE TITLE
GET /api/loans fails

### ISSUE THREAD

**Issue by JRProd** [smu-geode/uomi#17]
Correct endpoint request return Slim error.

https://github.com/smu-geode/uomi/blob/loans/src/lib/controller/LoanController.php

**Comment by JBarr96** [comment]
```
Warning: include(/var/www/uomi/lib/LoanController.php): failed to open stream: No such file or directory in /var/www/uomi/lib/autoload.php on line 9

Warning: include(): Failed opening '/var/www/uomi/lib/LoanController.php' for inclusion (include_path='.:') in /var/www/uomi/lib/autoload.php on line 9

Fatal error: Uncaught RuntimeException: Unexpected data in output buffer. Maybe you have characters before an opening <?php tag? in /var/www/uomi/vendor/slim/slim/Slim/App.php:585 Stack trace: #0 /var/www/uomi/vendor/slim/slim/Slim/App.php(377): Slim\App->finalize(Object(Slim\Http\Response)) #1 /var/www/uomi/vendor/slim/slim/Slim/App.php(295): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response)) #2 /var/www/uomi/api.php(23): Slim\App->run() #3 {main} thrown in /var/www/uomi/vendor/slim/slim/Slim/App.php on line 585
```

**Comment by phrz** [comment]
This issue is not attached to a branch so it's hard to know where to start looking. Link to file in the correct branch?

**Comment by phrz** [comment]
My first guess is you're accidentally referencing \Uomi\LoanController somewhere, and the auto loader is looking in /src/lib for stuff in the project namespace. LoanController is in /src/lib/controller and is under \Uomi\Controller\, so fix the namespace reference. I wrote an article under the wiki tab on PHP Namespaces if that helps.

**Comment by JRProd** [comment]
New error after fixing the permissions bug

{"type":"FastRoute\\BadRouteException","errorMessage":"Cannot register two routes matching \"\/api\/loans\/([^\/]+)\" for method \"GET\"","line":79,"file":"\/var\/www\/uomi\/vendor\/nikic\/fast-route\/src\/DataGenerator\/RegexBasedAbstract.php","trace":[{"file":"\/var\/www\/uomi\/vendor\/nikic\/fast-route\/src\/DataGenerator\/RegexBasedAbstract.php","line":20,"function":"addVariableRoute","class":"FastRoute\\DataGenerator\\RegexBasedAbstract","type":"->","args":["GET",["\/api\/loans\/",["loan_id","[^\/]+"]],"route5"]},{"file":"\/var\/www\/uomi\/vendor\/nikic\/fast-route\/src\/RouteCollector.php","line":36,"function":"addRoute","class":"FastRoute\\DataGenerator\\RegexBasedAbstract","type":"->","args":["GET",["\/api\/loans\/",["loan_id","[^\/]+"]],"route5"]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/Router.php","line":227,"function":"addRoute","class":"FastRoute\\RouteCollector","type":"->","args":[["GET"],"\/api\/loans\/{loan_id}","route5"]},{"file":"\/var\/www\/uomi\/vendor\/nikic\/fast-route\/src\/functions.php","line":24,"function":"Slim\\{closure}","class":"Slim\\Router","type":"->","args":[{}]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/Router.php","line":238,"function":"FastRoute\\simpleDispatcher","args":[{},{"routeParser":{},"dataGenerator":"FastRoute\\DataGenerator\\GroupCountBased","dispatcher":"FastRoute\\Dispatcher\\GroupCountBased","routeCollector":"FastRoute\\RouteCollector"}]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/Router.php","line":191,"function":"createDispatcher","class":"Slim\\Router","type":"->","args":[]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/App.php","line":546,"function":"dispatch","class":"Slim\\Router","type":"->","args":[{}]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/App.php","line":470,"function":"dispatchRouterAndPrepareRoute","class":"Slim\\App","type":"->","args":[{},{}]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php","line":122,"function":"__invoke","class":"Slim\\App","type":"->","args":[{},{}]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/App.php","line":370,"function":"callMiddlewareStack","class":"Slim\\App","type":"->","args":[{},{}]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/App.php","line":295,"function":"process","class":"Slim\\App","type":"->","args":[{},{}]},{"file":"\/var\/www\/uomi\/api.php","line":23,"function":"run","class":"Slim\\App","type":"->","args":[]}]}

**Comment by JRProd** [comment]
Error evolving. Had two gets for same route.

**Comment by JRProd** [comment]
Ping off of GET/api/users/1

{"type":"Error","errorMessage":"Class 'Uomi\\Controller\\Model\\User' not found","line":27,"file":"\/var\/www\/uomi\/lib\/controller\/UserController.php","trace":[{"function":"getUserHandler","class":"Uomi\\Controller\\UserController","type":"->","args":[{},{},{"user_id":"3"}]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php","line":41,"function":"call_user_func","args":[[{},"getUserHandler"],{},{},{"user_id":"3"}]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/Route.php","line":344,"function":"__invoke","class":"Slim\\Handlers\\Strategies\\RequestResponse","type":"->","args":[[{},"getUserHandler"],{},{},{"user_id":"3"}]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php","line":122,"function":"__invoke","class":"Slim\\Route","type":"->","args":[{},{}]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/Route.php","line":316,"function":"callMiddlewareStack","class":"Slim\\Route","type":"->","args":[{},{}]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/App.php","line":476,"function":"run","class":"Slim\\Route","type":"->","args":[{},{}]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php","line":122,"function":"__invoke","class":"Slim\\App","type":"->","args":[{},{}]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/App.php","line":370,"function":"callMiddlewareStack","class":"Slim\\App","type":"->","args":[{},{}]},{"file":"\/var\/www\/uomi\/vendor\/slim\/slim\/Slim\/App.php","line":295,"function":"process","class":"Slim\\App","type":"->","args":[{},{}]},{"file":"\/var\/www\/uomi\/api.php","line":23,"function":"run","class":"Slim\\App","type":"->","args":[]}]}

**Comment by JRProd** [comment]
Getting response back from server. Error with namespacing or some php shit. When commented out works like a champ. Issue resolved just need to not suck at PHP/Eloquent
