### ISSUE TITLE
JBarr Log in Error

### ISSUE THREAD

**Issue by JBarr96** [smu-geode/uomi#65]
Angular is running in the development mode. Call enableProdMode() to enable the production mode.  core.umd.js:3032:9
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More]  registration
{"email":"jeff@pear.com","password":"asdfasdfasdf"}  users-service.js:28:9
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data  users-service.js:48:9
ERROR TypeError: error._body is undefined
Stack trace:
UsersService.prototype.handleError@http://uomi.dev/app/services/users-service.js:55:13
CatchSubscriber.prototype.error@http://uomi.dev/node_modules/rxjs/operator/catch.js:53:26
MapSubscriber.prototype._next@http://uomi.dev/node_modules/rxjs/operator/map.js:80:13
Subscriber.prototype.next@http://uomi.dev/node_modules/rxjs/Subscriber.js:89:13
onLoad@http://uomi.dev/node_modules/@angular/http/bundles/http.umd.js:1213:21
ZoneDelegate.prototype.invokeTask@http://uomi.dev/node_modules/zone.js/dist/zone.js:398:17
onInvokeTask@http://uomi.dev/node_modules/@angular/core/bundles/core.umd.js:4123:28
ZoneDelegate.prototype.invokeTask@http://uomi.dev/node_modules/zone.js/dist/zone.js:397:17
Zone.prototype.runTask@http://uomi.dev/node_modules/zone.js/dist/zone.js:165:28
ZoneTask/this.invoke@http://uomi.dev/node_modules/zone.js/dist/zone.js:460:28
  core.umd.js:1091:5

**Comment by phrz** [comment]
This error cannot be reproduced as-is. Post a new issue with reproducibility steps if it still is a problem.
